name: Add solutions

on:
  # Run workflow on pushes to main branch
  issues:
    types: [closed]
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      issues: read
    if: ${{ github.event.issue.labels[1].name == 'accepted' }}
    env:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: |-
          git config --global user.email "arjun140702@gmail.com"
          git config --global user.name "Arjun"
          git pull
          pip install requests
          python3 script.py ${{ github.event.issue.number }}
          
      - name: Commit and push if changed
        run: |-
          git diff
          git add .
          git commit -m "Merge solution"
          git push
